export default ({
    namespaced: true,
    state: {
        movieSwiperArr:[
            {
                name:'后来的我们',
                id:'0001',
                img:require("@/assets/movie-imgs/cinemaInfo/swiper1.png"),
                time:'119分钟',
                class:'剧情、爱情',
                actor:'井柏然、周冬雨、田壮壮',
                session:[
                    {
                        startTime:'15:30',
                        endTime:'17:14',
                    },

                ]
            },
            {
                name:'文集',
                id:'0002',
                img:require("@/assets/movie-imgs/cinemaInfo/swiper2.png"),
                time:'75分钟',
                class:'剧情、爱情',
                actor:'郑帝元、申银秀、许真',
                session:[
                    {
                        startTime:'15:30',
                        endTime:'17:14',
                    },
                    {
                        startTime:'15:30',
                        endTime:'17:14',
                    },
                ]
            },
            {
                name:'傲慢与偏见',
                id:'0003',
                img:require("@/assets/movie-imgs/cinemaInfo/swiper3.png"),
                time:'129分钟',
                class:'剧情、爱情',
                actor:'凯拉·奈特莉、吉娜·马隆',
                session:[
                    {
                        startTime:'15:30',
                        endTime:'17:14',
                    },
                    {
                        startTime:'15:30',
                        endTime:'17:14',
                    },
                    {
                        startTime:'15:30',
                        endTime:'17:14',
                    },
                ]
            },
            {
                name:'梅子鸡之味',
                id:'0004',
                img:require("@/assets/movie-imgs/cinemaInfo/swiper4.png"),
                time:'93分钟',
                class:'喜剧',
                actor:'马修·阿马立克、歌什菲·法拉哈尼',
                session:[
                    {
                        startTime:'15:30',
                        endTime:'17:14',
                    },
                    {
                        startTime:'15:30',
                        endTime:'17:14',
                    },
                ]
            },
            {
                name:'裂缝',
                id:'0005',
                img:require("@/assets/movie-imgs/cinemaInfo/swiper5.png"),
                time:'104分钟',
                class:'剧情、伦理、惊悚',
                actor:'伊娃·格林、玛利亚·瓦沃德、朱诺·坦普尔',
                session:[
                    {
                        startTime:'15:30',
                        endTime:'17:14',
                    },
                    {
                        startTime:'15:30',
                        endTime:'17:14',
                    },
                    {
                        startTime:'15:30',
                        endTime:'17:14',
                    },
                    {
                        startTime:'15:30',
                        endTime:'17:14',
                    },
                    {
                        startTime:'15:30',
                        endTime:'17:14',
                    },
                ]
            },

        ]
    },
    mutations: {

    },
    actions: {
      
    }
  })
  